# Generated by Django 3.0.4 on 2020-03-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urunler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma', models.CharField(max_length=200)),
                ('adres', models.CharField(max_length=200)),
                ('urunTipi', models.CharField(max_length=200)),
                ('urunKategorisi', models.CharField(max_length=200)),
                ('urun', models.CharField(max_length=200)),
                ('hileGerekcesi', models.CharField(max_length=200)),
                ('etkenMadde', models.CharField(max_length=200)),
                ('marka', models.CharField(max_length=200)),
                ('partiNo', models.CharField(max_length=200)),
                ('enlem', models.IntegerField()),
                ('boylam', models.IntegerField()),
                ('tarih', models.CharField(max_length=200)),
            ],
        ),
    ]
